server {
    listen 80;
    server_name 192.168.1.74; # Ваш IP
    return 301 https://$host$request_uri; # Редирект на HTTPS
}

server {
    listen 443 ssl;
    server_name 192.168.1.74; # Ваш IP

    ssl_certificate /home/vboxuser/GetTogether/qr_test/cert.pem;
    ssl_certificate_key /home/vboxuser/GetTogether/qr_test/key.pem;

    # Фронтенд
    location / {
        root /home/vboxuser/GetTogether/Front/GetTogether/dist;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Бэкенд
    location /api/ {
        proxy_pass http://localhost:5000; # Бэк работает по HTTP на 5000 порту
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}